services:
  - type: web
    name: api-service
    env: python
    plan: free
    region: oregon  # or frankfurt for EU
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn api_service.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "api-service.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: api-service-db
          property: connectionString

databases:
  - name: api-service-db
    plan: free
